FROM node:22-bookworm-slim

WORKDIR /app

COPY package*.json ./
COPY apps/api/package*.json ./apps/api/
COPY apps/web/package*.json ./apps/web/
COPY packages/database/package*.json ./packages/database/
COPY packages/shared/package*.json ./packages/shared/

RUN npm ci

COPY . .

RUN npm run prisma:generate -w packages/database
RUN npm run build -w apps/api

EXPOSE 4000

CMD ["node", "apps/api/dist/main.js"]
